Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
      public enum MachineStatus
  {
    Operational = 0,
    Malfunctioning = 1,
    Being_Repaired = 2
  }
  public class Machine
  {
    [Required(ErrorMessage = "Machine name cannot be empty. Please enter a name.")]
    [StringLength(50, MinimumLength = 2, ErrorMessage = "Name should be between 2 and 50 characters")]
    public string Name { get; set; }
    [Required(ErrorMessage = "Description cannot be empty. Please enter a description.")]
    [RegularExpression(@"^(?=.*[^\s])\w[\w\s]*$", ErrorMessage = "Description should only contain letters and numbers")]
    [StringLength(1000, MinimumLength = 10, ErrorMessage = "Description should be between 10 and 100 characters")]
    public string Description { get; set; }
    public MachineStatus Status { get; set; } = (int)MachineStatus.Operational;
    public int MachineId { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
                              .Include(engineer => engineer.JoinEntities)
                              .ThenInclude(join => join.Machine)
                              .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (ModelState.IsValid)
      {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return View("Create");
      }
    }


    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      ViewBag.MachineCount = ((SelectList)ViewBag.MachineId).Count();
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
#nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }
    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers
                              .Include(Engineer => Engineer.JoinEntities)
                              .ThenInclude(join => join.Machine)
                              .FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (ModelState.IsValid)
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return View("Create");
      }
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
                            .Include(machine => machine.JoinEntities)
                            .ThenInclude(join => join.Engineer)
                            .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines
                            .Include(Machine => Machine.JoinEntities)
                            .ThenInclude(join => join.Engineer)
                            .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      ViewBag.EngineerCount = ((SelectList)ViewBag.EngineerId).Count();
      return View(thisMachine);
    }
    
    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
#nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
#nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1 class="text-center">Add an engineer to this machine</h1>
<hr>
<h4>Name: @Html.DisplayFor(model => model.Name)</h4>
<br>
@using (Html.BeginForm())
{
  if((int)@ViewBag.EngineerCount == 0)
  {
    <p>No engineers have been added yet!</p>
  }
  else
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select engineer")<br>
    @Html.DropDownList("EngineerId")

    <input type="submit" class="btn btn-primary" value="Save" />
  }
}
<br>
<hr class="my-2">
<p class="nav">@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

@* <p><strong>NOTE:</strong> You need to have at least one category before you can add an machine!</p> *@
@* <p>Go to @Html.ActionLink("this page", "Create", "Categories") to create a category.</p> *@
<h1 class="text-center">Add a new machine</h1>
<hr>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)<br>
  <p>@Html.TextBoxFor(model => model.Name)</p>
  <p class="text-danger">@Html.ValidationMessageFor(model => model.Name)</p>
  @Html.LabelFor(model => model.Description)<br>
  <p>@Html.TextBoxFor(model => model.Description)</p>
  <p class="text-danger">@Html.ValidationMessageFor(model => model.Description)</p>
  <p style="white-space: pre-line"></p>
  <input type="submit" value="Add new machine" class="btn btn-primary" />
}
<br>
<hr class="my-2">
<p class="nav ">@Html.ActionLink("Show all machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1 class="text-center">Are you sure you want to delete this?</h1>
<hr>
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-primary" />
}
<br>
<hr class="my-2">
@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h1 class="text-center">Machine Details</h1>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<p>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</p>
<p>@Html.DisplayNameFor(model => model.Status): @Html.DisplayFor(model => model.Status)</p>
<br>
@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine does not have any engineers yet!</p>
}
else
{
  <h4>This machine has the following engineers:</h4>
  <ul>
    @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li>Engineer: @Html.ActionLink(@join.Engineer.Name, "Details", "Engineers", new {id = @join.Engineer.EngineerId})</li>
    }
  </ul>
}

<hr class="my-2">
<p class="nav">@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
<p class="nav">@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p class="nav">@Html.ActionLink("Back to list", "Index")</p>
<p class="nav">@Html.ActionLink("Add a Engineer", "AddEngineer", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h1 class="text-center">Edit this machine</h1>
<hr>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.LabelFor(model => model.Name)<br>
    @Html.EditorFor(model => model.Name)<br> 
    <p class="mt-2 mb-0">@Html.LabelFor(model => model.Description)</p>
    @Html.EditorFor(model => model.Description)
    <p class="mb-0">@Html.LabelFor(model => model.Status)</p>
    <p class="mb-0">@Html.DropDownListFor(model => model.Status, new SelectList(Enum.GetValues(typeof(MachineStatus))), "Select Status")</p>
    <br>
    <input type="submit" value="Save"  class="btn btn-primary" />
  }
  <br>
  <h4>This machine has the following engineers:</h4>

  <ul>
    @foreach (EngineerMachine join in Model.JoinEntities)
      {
        <li>@join.Engineer.Name
        @using (Html.BeginForm("DeleteJoin", "Machines"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" class="btn btn-primary"  value="Delete"/>
        }
        </li>
      }
  </ul>

<br>
<hr class="my-2">
<p class="nav">@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Machine>;

<h1 class="text-center">Machines</h1>
<hr>

<ul>
  @foreach(Machine machine in Model)
  {
  <li>
    
    @Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId}) | @machine.Status
  </li>   
  }
    @* <a name="date">@Html.ActionLink("Sort by date", "Index", "Machines", new {sortBy = "date"})</a> *@
</ul>
<br>

<hr class="my-2">
<p class="nav">@Html.ActionLink("Add new machine", "Create")</p>
<p class="nav">@Html.ActionLink("Home", "Index", "Home")</p>